module.exports = {
  API_BASE_URL: 'https://api.test.rapidtriage.com',
  API_VERSION: 'v1',
  FIREBASE_API_KEY: 'test_firebase_api_key',
  FIREBASE_AUTH_DOMAIN: 'test.firebaseapp.com',
  FIREBASE_PROJECT_ID: 'test-project-id',
  FIREBASE_STORAGE_BUCKET: 'test-project-id.appspot.com',
  FIREBASE_MESSAGING_SENDER_ID: '123456789',
  FIREBASE_APP_ID: '1:123456789:web:test',
  STRIPE_PUBLISHABLE_KEY: 'pk_test_mock_publishable_key',
  APP_ENV: 'test',
  DEBUG_MODE: 'true',
  ENABLE_ANALYTICS: 'true',
  ENABLE_CRASH_REPORTING: 'false',
  GOOGLE_CLIENT_ID: 'mock_google_client_id',
  APPLE_CLIENT_ID: 'mock_apple_client_id',
  GITHUB_CLIENT_ID: 'mock_github_client_id',
  GITHUB_CLIENT_SECRET: 'mock_github_client_secret',
  STRIPE_PRO_PRICE_ID: 'price_mock_pro',
  STRIPE_TEAM_PRICE_ID: 'price_mock_team',
  STRIPE_ENTERPRISE_PRICE_ID: 'price_mock_enterprise',
};